name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  ROS2-CI:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Behavior Tree
        run: sudo apt update && sudo apt install ros-humble-behavior* -y

      - name: ROS2 Action CI
        uses: ros-tooling/action-ros-ci@0.4.1
        with:
          package-name: cod_behavior
          target-ros2-distro: humble
          vcs-repo-file-url: "${{ github.workspace }}/dependencies.repos"
          skip-tests: true

#  qodana:
#    runs-on: ubuntu-22.04
#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
#          fetch-depth: 0  # a full history is required for pull request analysis
#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.3
#        with:
#          pr-mode: false
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_571667025 }}
#          QODANA_ENDPOINT: 'https://qodana.cloud'