name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Behavior Tree
        run: sudo apt update && sudo apt install ros-humble-behavior* -y

      - name: Clone dependencies
        uses: ros-tooling/action-ros-ci@0.4.1
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: "${{ github.workspace }}/dependencies.repos"
          skip-tests: true
          skip-build: true

      - name: Build rm_interfaces first
        run: |
          source /opt/ros/humble/setup.sh
          cd ${{ github.workspace }}
          colcon build --packages-select rm_interfaces --event-handlers=console_cohesion+ --symlink-install
          source install/setup.sh

      - name: Build project
        run: |
          source /opt/ros/humble/setup.sh
          source ${{ github.workspace }}/install/setup.sh
          colcon build --event-handlers=console_cohesion+ --symlink-install

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_571667025 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'